"""empty message

Revision ID: 19779b5adbb4
Revises: 3000e48be35a
Create Date: 2023-11-20 17:04:51.716065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19779b5adbb4'
down_revision = '3000e48be35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_comments_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_favorites_poll_id_polls', type_='foreignkey')
        batch_op.drop_constraint('fk_favorites_issue_id_issues', type_='foreignkey')
        batch_op.drop_constraint('fk_favorites_discussion_id_discussions', type_='foreignkey')
        batch_op.drop_constraint('fk_favorites_organization_id_organizations', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_favorites_food_id_foods'), 'foods', ['food_id'], ['id'])
        batch_op.drop_column('discussion_id')
        batch_op.drop_column('issue_id')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('issue_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('discussion_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_favorites_food_id_foods'), type_='foreignkey')
        batch_op.create_foreign_key('fk_favorites_organization_id_organizations', 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key('fk_favorites_discussion_id_discussions', 'discussions', ['discussion_id'], ['id'])
        batch_op.create_foreign_key('fk_favorites_issue_id_issues', 'issues', ['issue_id'], ['id'])
        batch_op.create_foreign_key('fk_favorites_poll_id_polls', 'polls', ['poll_id'], ['id'])
        batch_op.drop_column('food_id')

    op.drop_table('comments')
    # ### end Alembic commands ###
