"""empty message

Revision ID: 3000e48be35a
Revises: 3e452b15a75f
Create Date: 2023-11-18 11:11:11.638603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3000e48be35a'
down_revision = '3e452b15a75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('contact1', sa.String(length=120), nullable=True),
    sa.Column('contact2', sa.String(length=120), nullable=True),
    sa.Column('contact3', sa.String(length=120), nullable=True),
    sa.Column('image1', sa.String(length=120), nullable=True),
    sa.Column('image2', sa.String(length=120), nullable=True),
    sa.Column('image3', sa.String(length=120), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants'))
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_foods_category_id_categories')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_foods_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_favorites_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_likes_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_likes_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorites_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    op.drop_table('foods')
    op.drop_table('restaurants')
    op.drop_table('categories')
    # ### end Alembic commands ###
